[build]
  base = "Frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  # do NOT set publish, let Next.js plugin handle it automatically

[[plugins]]
  package = "@netlify/plugin-nextjs"