[build]
  base = "Frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  # DO NOT set publish here â€” plugin will handle it automatically

[[plugins]]
  package = "@netlify/plugin-nextjs"